# Generated by Django 2.0.7 on 2019-02-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure'), ('I', 'Injured'), ('P', 'Pending response')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'Tournament'), ('S', 'Scrimmage')], max_length=20)),
                ('name', models.CharField(default='', max_length=30)),
                ('date', models.DateField(verbose_name='Event date')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('gender_line', models.CharField(choices=[('F', 'F-line'), ('M', 'M-line')], max_length=1)),
                ('field_position', models.CharField(choices=[('C', 'Cutter'), ('H', 'Handler'), ('Y', 'Hybrid')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='team.Attendance', to='team.Player'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Player'),
        ),
    ]
