# Generated by Django 2.0.7 on 2018-07-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'Tournament'), ('S', 'Scrimmage')], max_length=20)),
                ('event_name', models.CharField(default='', max_length=30)),
                ('date', models.DateField(verbose_name='tournament date')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('gender_line', models.CharField(choices=[('F', 'F-line'), ('M', 'M-line')], max_length=1)),
                ('field_position', models.CharField(choices=[('C', 'Cutter'), ('H', 'Handler'), ('Y', 'Hybrid')], max_length=1)),
            ],
        ),
    ]
