# Generated by Django 2.0.7 on 2018-07-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('team', '0002_event_attendees'), ('team', '0003_auto_20180719_1556'), ('team', '0004_attendance'), ('team', '0005_auto_20180720_1002')]

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Event date'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure'), ('I', 'Injured')], max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='team.Attendance', to='team.Player'),
        ),
    ]
