# Generated by Django 2.0.7 on 2018-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(to='team.Player'),
        ),
    ]
