# Generated by Django 2.1.7 on 2019-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
