# Generated by Django 2.0.7 on 2018-07-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_event_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Event date'),
        ),
    ]
