# Generated by Django 2.1.7 on 2019-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190501_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure'), ('P', 'Pending response')], default='P', max_length=1),
        ),
    ]
