# Generated by Django 2.0.7 on 2018-07-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180719_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure'), ('I', 'Injured')], max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
            ],
        ),
    ]
