# Generated by Django 2.1.7 on 2019-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20190503_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='captain_status',
            field=models.BooleanField(default=False),
        ),
    ]
