# Generated by Django 2.0.7 on 2018-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='team.Attendance', to='team.Player'),
        ),
    ]
